version: '3.7'

services:
    php-httpd:
        build:
            context: ./
        ports:
            - 80:80
        volumes:
            - "./:/var/www/html"
        environment:
            - 'TZ=Asia/Manila'
            - VIRTUAL_HOST=elecsystest.com
            - VIRTUAL_PORT=80
